Repository PoiPoi-Dev/PoiPoi-frontend, pull requests merged in 2024-06, with the labels that each got.

#11 Display POI mark and POI card on map | fix displaying mark bug
  app/_api/sample.ts
  app/_components/Map.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/ui/dialog.tsx
  app/_utils/global.d.ts
  app/map/page.tsx
  app/page.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/PinIcon.png
Labels: bug, enhancement

#13 Fix card | Animation | Position to display correctly.
  app/_components/MapContainer.tsx
  app/_components/ui/dialog.tsx
  app/_components/ui/popover.tsx
Labels: bug

#14 Display search zone
  app/_api/sample.ts
  app/_components/MapContainer.tsx
  app/_components/MarkerContainer.tsx
  app/_components/PoiCard.tsx
Labels: enhancement

#18 Separating collected POI and remove unnecessary data
  app/_api/sample.ts
  app/_components/MapContainer.tsx
  app/_components/MarkerContainer.tsx
  app/_utils/global.d.ts
  package-lock.json
  package.json
Labels: documentation, enhancement

#20 CICD week 2 #1
  .env.local.example
  .firebaserc
  .gitignore
  README.md
  app/_api/sample.ts
  app/_components/MapContainer.tsx
  app/_components/MapContextProvider.tsx
  app/_components/MapControls.tsx
  app/_components/MarkerContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/TagFilterDropdown.tsx
  app/_components/ui/button.tsx
  app/_components/ui/dialog.tsx
  app/_components/ui/popover.tsx
  app/_utils/authentication.ts
  app/_utils/extractTags.ts
  app/_utils/favicon.ico
  app/_utils/global.d.ts
  app/globals.css
  app/login/page.tsx
  app/map/page.tsx
  app/page.tsx
  components.json
  config/firebaseconfig.ts
  firebase.json
  lib/utils.ts
  next.config.mjs
  package-lock.json
  package.json
  public/Hachiko.jpg
  public/PinIcon.png
  tailwind.config.ts
Labels: enhancement

#23 Collect POI
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
Labels: enhancement

#25 fix: button will change to text when user click collect instantly
  app/_components/PoiCard.tsx
Labels: bug

#28 fix: fix styling and change img to NEXT Image components
  app/_components/MarkerContainer.tsx
  app/_components/PoidexModal.tsx
Labels: bug

#34 Connect to Backend with real data
  app/_api/sample.ts
  app/_components/DistanceHintButton.tsx
  app/_components/MapContainer.tsx
  app/_components/MarkerContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/PoidexModal.tsx
  app/_utils/global.d.ts
  next.config.mjs
Labels: bug, enhancement, help wanted

#35 Setup firebase authentication
  app/_actions/authenticationActions.ts
  app/_components/MapContainer.tsx
  app/_components/SubmitGuessButton.tsx
  app/_components/useContext/AuthContext.tsx
  app/_utils/authentication.ts
  app/_utils/extractTags.ts
  app/login/LoginPage.tsx
  app/login/page.tsx
  app/map/page.tsx
  config/firebaseconfig.ts
Labels: enhancement

#37 Feat/auth to validate user
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/login/LoginPage.tsx
Labels: enhancement

#38 implement guess button function PR
  app/_components/SubmitGuessButton.tsx
  app/_utils/global.d.ts
Labels: enhancement

#40 fix: CORS error by adding header + credentials
  app/_actions/authenticationActions.ts
  app/_components/MapContainer.tsx
  app/_components/SubmitGuessButton.tsx
Labels: bug

#42 Refactor/use closest pin
  app/_components/GameControls.tsx
  app/_components/MapContainer.tsx
  app/_components/Poidex.tsx
  app/_components/SubmitGuessButton.tsx
  app/_hooks/useGeolocation.ts
  app/_utils/coordinateMath.ts
  app/_utils/global.d.ts
Labels: enhancement

#43 Feat/guess line
  app/_components/FilterButton.tsx
  app/_components/HintButton.tsx
  app/_components/MapContainer.tsx
  app/_components/MarkerContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/PoidexModal.tsx
  app/_components/ui/drawer.tsx
  app/_components/ui/guessPolyline.tsx
  app/_utils/global.d.ts
  package-lock.json
  package.json
Labels: enhancement

#46 Feat/guess within zone
  app/_components/GameControls.tsx
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/PopoverCard.tsx
Labels: enhancement

#50 feat: the button from the poi card can now set a pin to track if the …
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/useContext/TrackingPinContext.tsx
Labels: enhancement

#52 Feat/sign user out
  app/_actions/authenticationActions.ts
  app/_utils/authentication.ts
  app/login/LoginPage.tsx
Labels: enhancement

#53 Feat/poi card submit to db
  app/_components/GameControls.tsx
  app/_components/PoiCard.tsx
  app/_components/PoidexModal.tsx
Labels: bug, enhancement

#54 Style/styling UI
  app/_components/FilterButton.tsx
  app/_components/GameControls.tsx
  app/_components/GuessDistanceModal.tsx
  app/_components/MainQuest.tsx
  app/_components/MapContainer.tsx
  app/_components/MapControls.tsx
  app/_components/MarkerContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPhotoToggle.tsx
  app/_components/PoiPopup.tsx
  app/_components/Poidex.tsx
  app/_components/PoidexModal.tsx
  app/_components/PopoverCard.tsx
  app/_components/SubmitGuessButton.tsx
  app/_components/ui/MenuIconCircle.tsx
  app/_components/ui/badge.tsx
  app/_components/ui/dialog.tsx
  app/_components/ui/drawer.tsx
  app/_components/ui/drawerCloseButton.tsx
  app/_utils/global.d.ts
  app/globals.css
  app/map/page.tsx
Labels: enhancement

#56 Bugfix/fixing rendering hintmodal
  app/_components/GuessDistanceModal.tsx
  app/_components/HintModal.tsx
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/SubmitGuessButton.tsx
  app/_components/useContext/ImportantPinContext.tsx
Labels: bug, enhancement

#60 Styling for leaderboard, Login, PoiDex, and overall UI improvement
  app/_components/FooterMenu.tsx
  app/_components/GameControls.tsx
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/Poidex.tsx
  app/_components/PoidexModal.tsx
  app/_components/ui/MenuIconCircle.tsx
  app/_components/ui/button.tsx
  app/_components/ui/input.tsx
  app/_components/ui/label.tsx
  app/_components/ui/table.tsx
  app/_components/useContext/AuthContext.tsx
  app/_utils/authentication.ts
  app/_utils/global.d.ts
  app/globals.css
  app/leaderboard/Leaderboard.tsx
  app/login/LoginPage.tsx
  app/login/page.tsx
  app/page.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement

#62 Feat/quest tracker button
  app/_components/FilterButton.tsx
  app/_components/MainQuest.tsx
  app/_components/MapContainer.tsx
  app/_components/MapControls.tsx
  app/_components/PoiCard.tsx
  app/_components/useContext/TrackingPinContext.tsx
Labels: enhancement

#69 Fix/maplibre viewport bug
  app/_components/GuessDistanceModal.tsx
  app/_components/MapContainer.tsx
  app/globals.css
  app/login/LoginPage.tsx
Labels: bug

#70 Fix/stop pan after guess
  app/_components/MainQuest.tsx
  app/_components/MapControls.tsx
  app/_components/PoiCard.tsx
Labels: bug

#72 Hint Toast PR
  app/_components/PoiCard.tsx
  app/_components/ui/sonner.tsx
  package-lock.json
  package.json
Labels: enhancement

#71 Refactor/guessPolyLine and GuessDistanceModal have relevant information passed from MapContainer
  app/_components/GuessDistanceModal.tsx
  app/_components/MapContainer.tsx
  app/_components/PoiCard.tsx
  app/_components/PoiPopup.tsx
  app/_components/PopoverCard.tsx
Labels: enhancement

#74 Style/hint account etc
  app/_components/FilterButton.tsx
  app/_components/MainQuest.tsx
  app/_components/PoiCard.tsx
  app/_components/ui/button.tsx
  app/globals.css
  app/layout.tsx
Labels: enhancement

#77 Feat/pan camera from poi collection
  app/_components/MainQuest.tsx
  app/_components/MapContainer.tsx
  app/_components/MapContextProvider.tsx
  app/_components/PoidexModal.tsx
Labels: enhancement

#79 Bugfix/remove excess input and button
  app/_components/GuessDistanceModal.tsx
Labels: bug

#81 fix: prevent user from seeing the sign out window on an unsuccessful account creation
  app/login/LoginPage.tsx
Labels: bug

#88 fix: z-index bug and restyle to sub-menu
  app/map/page.tsx
Labels: bug, enhancement

#91 style: relocate state to check if user open poiDex, default will acti…
  app/_components/GameControls.tsx
  app/_components/Poidex.tsx
Labels: enhancement

#89 fix: pinch-zoom on div, map still zoomable
  app/globals.css
Labels: bug

#93 style: relocate state to check if user open poiDex
  app/_components/GameControls.tsx
  app/_components/Poidex.tsx
Labels: bug, enhancement

#94 Fix/guess distance modal display distance
  app/_components/GuessDistanceModal.tsx
Labels: bug

#95 chore: add comment to handleSetClosestNotCompletedPin to indicate tha…
  app/_components/MapContainer.tsx
Labels: enhancement

#97 fix:z-index of user to 30 (markers is 40)
  app/globals.css
Labels: bug

#98 feat: navigate user to map after succesfully login
  app/_actions/authenticationActions.ts
  app/_components/LevelContainer.tsx
  app/login/LoginPage.tsx
Labels: enhancement

#96 Feat,style/account user data
  app/_actions/authenticationActions.ts
  app/_components/CircularXp.tsx
  app/_components/PoidexModal.tsx
  app/_components/ui/loading.tsx
  app/_utils/global.d.ts
  app/login/LoginPage.tsx
  tailwind.config.ts
Labels: enhancement

#100 Feat/adjust geolocation zoom
  app/_components/MapControls.tsx
Labels: enhancement

#101 Feat/poi photo toggle uses filters
  app/_components/MapContainer.tsx
  app/_components/PoiPhotoToggle.tsx
  app/_utils/coordinateMath.ts
Labels: enhancement

#105 feat,style: use Suspense for loading stage in multiple page.
  app/_components/ui/loading.tsx
  app/_components/ui/skeleton.tsx
  app/leaderboard/layout.tsx
  app/leaderboard/loading.tsx
  app/leaderboard/page.tsx
  app/login/LoginPage.tsx
  app/map/layout.tsx
  app/map/loading.tsx
Labels: enhancement

#107 feat: use Params to trigger the open state of collection
  app/_components/FooterMenu.tsx
  app/_components/Poidex.tsx
Labels: enhancement

#108 Style/hide uncollected title name
  app/_components/PoiCard.tsx
  app/_components/PoidexModal.tsx
Labels: enhancement

#109 style: adjust progress bar position and style
  app/_components/LevelContainer.tsx
  app/_components/ui/Progress.tsx
Labels: enhancement

#111 Style/leaderboard scrollable
  app/_components/ui/table.tsx
  app/_utils/fetchLeaderboard.ts
Labels: enhancement

#104 Feat/tracking pin in local storage
  app/_actions/authenticationActions.ts
  app/_components/MainQuest.tsx
  app/_components/MapContainer.tsx
  app/_components/MapControls.tsx
  app/_components/PoiCard.tsx
  app/_utils/global.d.ts
  app/_utils/localStorageHandler.ts
Labels: enhancement

#115 fix: remove bouncing effect on camera while following user
  app/_components/MapControls.tsx
Labels: bug

#117 fix hint button PR
  app/_components/PoiCard.tsx
Labels: bug

#121 chore: reset fit bound options to original settings
  app/_components/MapControls.tsx
Labels: bug

#113 chore: change h-screen to h-[100svh], disable input zoom on iOS
  app/_components/PoiPopup.tsx
  app/_components/PoidexModal.tsx
  app/_components/PopoverCard.tsx
  app/_components/ui/dialog.tsx
  app/_components/ui/loading.tsx
  app/globals.css
  app/login/LoginPage.tsx
  app/login/page.tsx
  app/map/layout.tsx
  app/page.tsx
Labels: bug

#147 feat: can open collection from other menus
  app/_components/FooterMenu.tsx
  app/_components/MapContainer.tsx
  app/_components/Poidex.tsx
Labels: bug

#144 Feat,style: landing page w/ middleware to check mobile or desktop
  app/globals.css
  app/how-to-play/HowToPlay.tsx
  app/how-to-play/page.tsx
  app/landing/layout.tsx
  app/landing/page.tsx
  app/login/page.tsx
  app/page.tsx
  middleware.ts
  next.config.mjs
  public/QRcode.png
Labels: enhancement

#154 fix: guess window z-50 -> z-60
  app/_components/GuessDistanceModal.tsx
Labels: bug

#162 style: remove padding that let landing can scroll sideway
  app/landing/page.tsx
Labels: bug
